package setup

import (
	"strings"
	"testing"
)

func TestHostResolvConfPutsLoopbackFirst(t *testing.T) {
	got := hostResolvConf()
	lines := strings.Split(strings.TrimSpace(got), "\n")
	var nameservers []string
	for _, l := range lines {
		if strings.HasPrefix(l, "nameserver ") {
			nameservers = append(nameservers, strings.TrimPrefix(l, "nameserver "))
		}
	}
	if len(nameservers) != 2 || nameservers[0] != "127.0.0.1" || nameservers[1] != hostResolverFallback {
		t.Errorf("nameservers = %v, want loopback then %s", nameservers, hostResolverFallback)
	}
	if !strings.Contains(got, hostResolverMarker) {
		t.Error("the file must carry the ctdev marker so detection can tell it from a hand edit")
	}
}

func TestDetectHostResolverContent(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{"ctdev-managed file", hostResolvConf(), "applied"},
		{"tailscale-generated file", "# resolv.conf(5) file generated by tailscale\nnameserver 100.100.100.100\n", "not applied"},
		{"NetworkManager file pointing at the LAN address", "# Generated by NetworkManager\nnameserver 10.2.2.144\n", "not applied"},
		{"loopback first but written by hand", "nameserver 127.0.0.1\nnameserver 1.1.1.1\n", "not applied"},
		{"unreadable", "", "not applied"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := detectHostResolverContent(tt.content); got != tt.want {
				t.Errorf("got %q, want %q", got, tt.want)
			}
		})
	}
}

func TestMagicDNSForwardRecord(t *testing.T) {
	got := magicDNSForwardRecord("tail3c73d9.ts.net")
	if !strings.Contains(got, "server=/tail3c73d9.ts.net/100.100.100.100") {
		t.Errorf("record = %q", got)
	}
	if got := magicDNSForwardRecord(""); got != "" {
		t.Errorf("no suffix should produce no record, got %q", got)
	}
}
